language: node_js
node_js:
- stable
install: npm update
addons:
  postgresql: '9.6'
  ssh_known_hosts: kvnneff.me
services:
- postgresql
cache:
  directories:
  - node_modules
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy
- ssh-add .travis/deploy
- echo -e "Host nestbox.kvnneff.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git remote add dokku dokku@kvnneff.me:nestbox.kvnneff.me
- git push dokku master
env:
  global:
  - NODE_ENV=test
before_install:
- openssl aes-256-cbc -K $encrypted_f4dd25c14a44_key -iv $encrypted_f4dd25c14a44_iv
  -in .travis/deploy.enc -out .travis/deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy
- ssh-add .travis/deploy
